# Generated by Django 2.2.4 on 2020-12-04 09:39

from django.db import migrations
from django.db.models import Case, Value, When

def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(
        new_building=Case(
            When(construction_year__gte=2015, then=Value(True)),
            default=Value(False))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [migrations.RunPython(fill_new_building_field), ]
