# Generated by Django 2.2.4 on 2020-12-04 11:17

from django.db import migrations
import phonenumbers


def fill_normalized_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_number):
            flat.owners_pure_phone = phonenumbers.format_number(
                parsed_number, phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owners_pure_phone = None
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owners_pure_phone'),
    ]

    operations = [migrations.RunPython(fill_normalized_number), ]
