# Generated by Django 2.2.4 on 2020-12-04 12:36

from django.db import migrations


def make_link_owner_to_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owners_pure_phone=flat.owners_pure_phone)[0]
        flat.flat_owners.add(owner)
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_auto_20201204_1448'),
    ]

    operations = [migrations.RunPython(make_link_owner_to_flats)
                  ]
